#!/bin/bash

if [ $1 = "?" ] 
then 
	echo Программа заменяет суффиксы файлов в директории на первый символ в названии этого файла, если его размер меньше заданного. Если не хотите выполнять данное действие, нажмите ctrl+c.
else
echo "Bведите размер файла:"
read size

	for file in "$(pwd)"/*
	do
		if [ "$( ls "$file" )" !=  "/home/artur/Рабочий стол/polinina_laba/script" ] && [ $(stat -c %s "$file") -lt $size ] && [ -f "$file" ]
		then 
		echo "Вы согласны поменять суффикс файлa $(ls "$file") в данной директории? (y/n)"
		read agree

			if [ $agree = "y" ]
			then
				newfile="${file/$(pwd)\//}"
				newfile=$(echo $newfile | sed 's/\.[^.]*$//')
				newfile=$(echo "$newfile.${newfile:0:1}")
				mv "$file" "$newfile"
			fi

		fi
	done
fi
